module.exports = {
  DB: process.env.DB || 'mongodb://atlasclinic:atlasclinic@cluster0-shard-00-00.barb6.mongodb.net:27017,cluster0-shard-00-01.barb6.mongodb.net:27017,cluster0-shard-00-02.barb6.mongodb.net:27017/atlas-clinic?ssl=true&replicaSet=atlas-cj4kqm-shard-0&authSource=admin&retryWrites=true&w=majority',
  IS_CONSOLE_LOG: process.env.IS_CONSOLE_LOG || 'true',
  PORT: process.env.PORT || '3001',
  WEBAPP_URL: process.env.WEBAPP_URL || 'http://atlas-90592714.us-east-1.elb.amazonaws.com',
  NOTIFICATION_EXCHANGE: process.env.NOTIFICATION_EXCHANGE || "notification_exchange",
  NOTIFICATION_QUEUE: process.env.NOTIFICATION_QUEUE || 'notification_queue_dev',
  AMQP_HOST_URL: process.env.AMQP_HOST_URL || 'amqp://user:bitnami@54.91.115.9:5672',
  COMMUNICATION_SERVICE_URL: 'http://atlas-90592714.us-east-1.elb.amazonaws.com:3004/',
  SPECIALITY_ID: process.env.SPECIALITY_ID || '6022bc35d9be3ffa6fe70b77',
  AMBRA_ACCOUNT_ID: process.env.AMBRA_ACCOUNT_ID || '2b826d7a-2616-4bfe-908c-65bf5e0e49f0',
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || 'atlas123atlas123',
  ALGORITHM: process.env.ALGORITHM || 'aes-128-cbc',
  ENCRYPTION_NUMBER: process.env.ENCRYPTION_NUMBER || '0000000000000000',
  AUTH_CLIENT_ID: process.env.AUTH_CLIENT_ID || 'b17TvDzTntozCloB66nfDNI6JiADdhhV',
  AUTH_DOMAIN: process.env.AUTH_DOMAIN || 'https://atlasclinic.us.auth0.com',
  AUTH_SECRET_KEY: process.env.AUTH_SECRET_KEY || '_DrwRHojkbLwQq1Fi_Y3mULZVG59wM-s_W2xNtgPeN-ovJ6wE9w6KjyzrFvGDKAX',
  SENDER_EMAIL: process.env.SENDER_EMAIL || 'jyotk@leewayhertz.com',
  BUCKET: process.env.BUCKET || "atlas-clinic-dev",
  ACCESS_KEY_ID: process.env.ACCESS_KEY_ID || "AKIAQFSYAU3R5AC4CNBX",
  SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY || "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",
  REGION: process.env.REGION || 'us-east-1',
  S3URL: process.env.S3URL || 'http://s3.us-east-1.amazonaws.com/atlas-clinic-dev/',
  S3_DOCUMENT_BUCKET: process.env.S3_DOCUMENT_BUCKET || 'atlas-clinic-dev/pdf-files',
  EXPIRY_TIME: process.env.EXPIRY_TIME || 432000,
  CRON_TIME_THRESHOLD: process.env.CRON_TIME_THRESHOLD || 2 * 60 * 1000,
  USER_SERVICE_URL: process.env.USER_SERVICE_URL || 'http://atlas-90592714.us-east-1.elb.amazonaws.com:3005',
}
